spring:
  config:
    import:
      - s3bucket.yml
      - redis.yml

  sql:
    init:
      mode: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:h2:mem:billage
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect # Spatial Dialect 설정
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQLSpatialDialect # Spatial Dialect 설정
        format_sql: true
        show_sql: true

  mail:
    host: smtp.naver.com
    port: 587
    username: ${NAVER_MAIL}
    password: ${NAVER_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    include: oauth


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          # 구글 로그인 추가
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile


jwt:
  secret: ${JWT_SECRET_KEY} ##임시 키
  token:
    refresh-expires: 604800000 # 7일
    access-expires: 3600000 # 60분

logging:
  level:
    org:
      springframework:
        security: DEBUG


custom:
  category-image:
    base-url: ${CATEGORY_IMAGE_BASEURL}

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGIN_URL}
  oauth2:
    authorized-redirect-urls: ${OAUTH_REDIRECT_URL}
    after-authorize-redirect-url: ${AFTER_OAUTH_REDIRECT_URL}

server:
  servlet:
    session:
      cookie:
        same-site: none